name: "acceptance"

on: [pull_request]

jobs:
  LitmusAcceptance:
    runs-on: self-hosted
    strategy:
      matrix:
        ruby_version: [2.5.x]
        puppet_gem_version: [~> 6.0]
        platform: [release_checks]
        agent_family: ['puppet6']
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: checkoutLFS
      uses: actions/checkout@v2
    - run: git lfs pull
    - name: Litmus Parallel
      uses: puppetlabs/action-litmus_parallel@master
      with:
        platform: ${{ matrix.platform }}
        agent_family: ${{ matrix.agent_family }}
  LitmusAcceptanceDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Build
      run: |
        gem install bundler
        bundle install --path .bundle/gems --jobs 4 --retry 3
        bundle exec rake spec_prep
    - name: Provision and setup
      run: |
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US:en
        bundle exec rake 'litmus:provision_list[release_checks_docker]'
        bundle exec rake litmus:install_agent
        bundle exec rake litmus:install_module
        bundle exec bolt --modulepath spec/fixtures/modules -i inventory.yaml command run 'yum install dhclient -y' -t 'localhost:2222' #amazon linux 2 needs this installed for networking/java to play nice
    - name: Inventory
      run: |
        cat ./inventory.yaml
    - name: Run tests
      run: |
        env
        bundle exec rake litmus:acceptance:parallel
    - name: Tidy up
      if: always()
      run: |
        bundle exec rake litmus:tear_down